name: Assign reviewers

on:
  pull_request:
    branches:
      - master
      - main
    types:
      - opened
      - reopened
      - synchronize
      - review_requested
      - review_request_removed
      - ready_for_review
  pull_request_review:

jobs:
  pr-custom-review:
    runs-on: ubuntu-latest
    steps:
      - name: Skip if pull request is in Draft
        if: github.event.pull_request.draft == true
        run: exit 1
      - name: pr-custom-review
        uses: paritytech/pr-custom-review@v2
        with:
          token: ${{ secrets.PRCR_TOKEN }}
